src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    private $date_debut;

    #[ORM\Column(type: 'date')]
    private $date_fin;

    #[ORM\Column(type: 'string', length: 255)]
    private $formateur;

    #[ORM\ManyToOne(targetEntity: Service::class, inversedBy: 'formations')]
    private $Service;

    #[ORM\ManyToOne(targetEntity: Technologie::class, inversedBy: 'formations')]
    private $Technologie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getFormateur(): ?string
    {
        return $this->formateur;
    }

    public function setFormateur(string $formateur): self
    {
        $this->formateur = $formateur;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->Service;
    }

    public function setService(?Service $Service): self
    {
        $this->Service = $Service;

        return $this;
    }

    public function getTechnologie(): ?Technologie
    {
        return $this->Technologie;
    }

    public function setTechnologie(?Technologie $Technologie): self
    {
        $this->Technologie = $Technologie;

        return $this;
    }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut')
            ->add('date_fin')
            ->add('formateur')
            ->add('Service')
            ->add('technologie');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/formation')]
class FormationController extends AbstractController
{
    #[Route('/', name: 'formation_index', methods: ['GET'])]
    public function index(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/index.html.twig', [
            'formations' => $formationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'formation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $formation = new Formation();
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'formation_show', methods: ['GET'])]
    public function show(Formation $formation): Response
    {
        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    #[Route('/{id}/edit', name: 'formation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Formation $formation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/edit.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'formation_delete', methods: ['POST'])]
    public function delete(Request $request, Formation $formation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('formation_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
	<div class="card-footer">
		<button class="btn btn-danger text-white">Delete</button>

	</div>
</form>

templates/formation/_form.html.twig
<form action="{{path('formation_new')}}" method="post">
	<div class="card-body">
		<div class="form-group">
			<label for="exampleInputdate">Date Debut</label>
			<input type="date" name="date" class="form-control" placeholder="Enter date">
		</div>
		<div class="form-group">
			<label for="exampleInputdate">Date Fin
			</label>
			<input type="date" name="date" class="form-control" placeholder="Enter date">
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Formateur
			</label>
			<input type="text" class="form-control" name="formateur" placeholder="formateur">
		</div>


		<div class="form-group">
			<label for="exampleInputNom">Service
			</label>
			<input type="text" class="form-control" name="service">
		</div>
		<div class="form-group">
			<label for="exampleInputPrenom">Technologie
			</label>
			<input type="text" class="form-control" name="technologie">
		</div>


	</div>
	<!-- /.card-body -->

	<div class="card-footer">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</form>

templates/formation/edit.html.twig
{% extends 'layouts/master.html.twig' %}

{% block title %}Modifier Formation
{% endblock %}

{% block content %}
	<h1>Modifier Formation</h1>

	{{ include('formation/_form.html.twig', {'button_label': 'Update'}) }}
	<div class="card-footer">
		<button class="btn btn-info " type="submit">
			<a href="{{ path('formation_index') }}" class="text-white">back to list</a>

		</button>
	</div>


	{{ include('formation/_delete_form.html.twig') }}
{% endblock %}

templates/formation/index.html.twig
{% extends 'layouts/master.html.twig' %}

{% block title %}Affichage Formation 
{% endblock %}

{% block content %}
	<h1>Formation </h1>

	<table class="table table-stripped table-hover">
		<thead>
			<tr>
				<th>Id</th>
				<th>Date_debut</th>
				<th>Date_fin</th>
				<th>Formateur</th>
				<th>technologie</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for formation in formations %}
				<tr>
					<td>{{ formation.id }}</td>
					<td>{{ formation.dateDebut ? formation.dateDebut|date('Y-m-d') : '' }}</td>
					<td>{{ formation.dateFin ? formation.dateFin|date('Y-m-d') : '' }}</td>
					<td>{{ formation.formateur }}</td>
					<td>{{ formation.technologie.nom}}</td>

					<td>
						<button class="btn btn-outline-primary" type="submit">
							<a href="{{ path('formation_show', {'id': formation.id}) }}">show</a>

						</button>
						{% if is_granted('ROLE_ADMIN') %}

							<button class="btn btn-outline-primary" type="submit">
								<a href="{{ path('formation_edit', {'id': formation.id}) }}">edit</a>

							</button>
						{% endif %}

					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% if is_granted('ROLE_ADMIN') %}

		<button class="btn btn-outline-primary" type="submit">
			<a href="{{ path('formation_new') }}">Create new</a>

		</button>
	{% endif %}

{% endblock %}

templates/formation/new.html.twig
{% extends 'layouts/master.html.twig' %}

{% block title %}Nouveau Formation
{% endblock %}

{% block content %}
	<h1>Ajouter nouveau Formation</h1>

	{{ include('formation/_form.html.twig') }}
	<div class="card-footer">
		<button class="btn btn-info " type="submit">
			<a href="{{ path('formation_index') }}" class="text-white">back to list</a>

		</button>
	</div>

{% endblock %}

templates/formation/show.html.twig
{% extends 'layouts/master.html.twig' %}

{% block title %}Affichage Formation
{% endblock %}

{% block content %}
	<h1>Formation</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ formation.id }}</td>
			</tr>
			<tr>
				<th>Date_debut</th>
				<td>{{ formation.dateDebut ? formation.dateDebut|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Date_fin</th>
				<td>{{ formation.dateFin ? formation.dateFin|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Formateur</th>
				<td>{{ formation.formateur }}</td>
			</tr>
			<tr>
				<th>Technologie</th>
				<td>{{ formation.technologie.nom  }}</td>
			</tr>
		</tbody>
		<tfooter>
			<tr>
				<td>
					<button class="btn btn-info" type="submit">
						<a href="{{ path('formation_index') }}" class="text-white">back to list</a>

					</button>
				</td>
			</tr>
			{% if is_granted('ROLE_ADMIN') %}

				<tr>
					<td>
						<button class="btn btn-success" type="submit">
							<a href="{{ path('formation_edit', {'id': formation.id}) }}" class="text-white">edit</a>

						</button>
					</td>
				</tr>
			{% endif %}

		</tfooter>
	</table>
	{% if is_granted('ROLE_ADMIN') %}


		{{ include('formation/_delete_form.html.twig') }}
	{% endif %}

{% endblock %}