src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    public $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'integer')]
    public $num_telephone;

    #[ORM\ManyToOne(targetEntity: Service::class, inversedBy: 'users')]
    private $Service;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return  array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNumTelephone(): ?int
    {
        return $this->num_telephone;
    }

    public function setNumTelephone(int $num_telephone): self
    {
        $this->num_telephone = $num_telephone;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->Service;
    }

    public function setService(?Service $Service): self
    {
        $this->Service = $Service;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\CallbackTransformer;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')

            ->add('password')
            ->add('nom')
            ->add('prenom')
            ->add('num_telephone');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
	<div class="card-footer">

		<button class="btn btn-danger text-white">Delete</button>
	</div>
</form>

templates/user/_form.html.twig
<form action="{{path('user_new')}}" method="post">
	<div class="card-body">
		<div class="form-group">
			<label for="exampleInputEmail1">Email</label>
			<input type="text" value="{{app.user.email}}" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Password
			</label>
			<input type="password" class="form-control" value="{{app.user.password}}" name="password" id="exampleInputPassword1" placeholder="Password">
		</div>


		<div class="form-group">
			<label for="exampleInputNom">Nom
			</label>
			<input type="text" class="form-control" value="{{app.user.nom}}" name="nom" id="">
		</div>
		<div class="form-group">
			<label for="exampleInputPrenom">Prenom
			</label>
			<input type="text" class="form-control" value="{{app.user.prenom}}" name="prenom" id="">
		</div>
		<div class="form-group">
			<label for="exampleInputtelephone">Numéro télephone
			</label>
			<input type="number" class="form-control" name="num_telephone" value="{{app.user.num_telephone}}" id="">
		</div>

	</div>
	<!-- /.card-body -->

	<div class="card-footer">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</form>

templates/user/edit.html.twig
{% extends 'layouts/master.html.twig' %}

{% block title %}Modifier utilisateur
{% endblock %}

{% block content %}
	<h1>Edit User</h1>

	{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}
	<div class="card-footer">
		<button class="btn btn-info " type="submit">
			<a href="{{ path('user_index') }}" class="text-white">back to list</a>

		</button>
	</div>

	{{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'layouts/master.html.twig' %}

{% block title %}
	Les utilisateurs
{% endblock %}

{% block content %}
	<h1>Les coordonnées d'utilisateur </h1>

	<table class="table table-stripped table-hover">
		<thead>
			<tr>
				<th>Id</th>
				<th>Email</th>
				{#}<th>Password</th> {#}
				<th>Nom</th>
				<th>Prenom</th>
				<th>Num_telephone</th>
				<th>service</th>

				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for user in users %}
				<tr>
					<td>{{ user.id }}</td>
					<td>{{ user.email }}</td>
					{#}	<td>{{ user.password }}</td> {#}
					<td>{{ user.nom }}</td>
					<td>{{ user.prenom }}</td>
					<td>{{ user.numTelephone }}</td>
					<td>{{ user.service }}</td>
					<td>
						<button class="btn btn-outline-primary" type="submit">
							<a href="{{ path('user_show', {'id': user.id}) }}">show</a>
						</button>


						<button class="btn btn-outline-primary" type="submit">
							<a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

						</button>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="8">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<button class="btn btn-outline-primary" type="submit">
		<a href="{{ path('user_new') }}">Create new</a>
	</button>
{% endblock %}

templates/user/new.html.twig
{% extends 'layouts/master.html.twig' %}

{% block title %}Ajouter utilisateur
{% endblock %}


{% block content %}
	<h1>Ajouter Utilisateur
	</h1>

	{{ include('user/_form.html.twig') }}

	<div class="card-footer">
		<button class="btn btn-info " type="submit">
			<a href="{{ path('user_index') }}" class="text-white">back to list</a>

		</button>
	</div>
{% endblock %}

templates/user/show.html.twig
{% extends 'layouts/master.html.twig' %}

{% block title %}Affichage d'utilisateur
{% endblock %}

{% block content %}
	<h1>Utilisateur
	</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ user.id }}</td>
			</tr>
			<tr>
				<th>Email</th>
				<td>{{ user.email }}</td>
			</tr>
			<tr>
				<th>Roles</th>
				<td>{{ user.roles ? user.roles|json_encode : '' }}</td>
			</tr>
			<tr>{#}	<th>Password</th> {#}
				{#}<td>{{ user.password }}</td> {#}
			</tr>
			<tr>
				<th>Nom</th>
				<td>{{ user.nom }}</td>
			</tr>
			<tr>
				<th>Prenom</th>
				<td>{{ user.prenom }}</td>
			</tr>
			<tr>
				<th>Num_telephone</th>
				<td>{{ user.numTelephone }}</td>
			</tr>
		</tbody>
		<tfooter>
			<tr>
				<td>
					<button class="btn btn-info" type="submit">
						<a href="{{ path('user_index') }}" class="text-white">back to list</a>

					</button>
				</td>
			</tr>
			<tr>
				<td>
					<button class="btn btn-success" type="submit">
						<a href="{{ path('user_edit', {'id': user.id}) }}" class="text-white">edit</a>

					</button>
				</td>
			</tr>
			<tr>
				<td>
					{{ include('user/_delete_form.html.twig') }}

				</td>
			</tr>
		</tfooter>
	</table>


{% endblock %}